---
    deployment:
        tasks:
            - export DEPLOYPATH=/home/ndzalyon/public_html/
            - /bin/cp index.html $DEPLOYPATH
            - /bin/cp style.css
            - /bin/cp -R images $DEPLOYPATH